"""Common canonical primitives for HotelOps AI contracts."""

from contracts.common.ids import (
    ActionCommandId,
    AlertId,
    AnalysisJobId,
    ApprovalRequestId,
    DetectionId,
    EventId,
    EvidenceId,
    FindingId,
    FrameId,
    MembershipId,
    OpportunityId,
    RecommendationId,
    RoleId,
    TenantId,
    TrackId,
    UserId,
    VenueId,
    VideoAssetId,
    VideoSessionId,
    new_uuid,
)
from contracts.common.time import (
    parse_utc,
    serialize_utc,
    to_utc,
    utc_now,
    validate_utc,
)
from contracts.common.versioning import (
    SCHEMA_VERSION,
    validate_schema_version,
)

__all__ = [
    "SCHEMA_VERSION",
    "ActionCommandId",
    "AlertId",
    "AnalysisJobId",
    "ApprovalRequestId",
    "DetectionId",
    "EventId",
    "EvidenceId",
    "FindingId",
    "FrameId",
    "MembershipId",
    "OpportunityId",
    "RecommendationId",
    "RoleId",
    "TenantId",
    "TrackId",
    "UserId",
    "VenueId",
    "VideoAssetId",
    "VideoSessionId",
    "new_uuid",
    "parse_utc",
    "serialize_utc",
    "to_utc",
    "utc_now",
    "validate_schema_version",
    "validate_utc",
]
