"""Canonical contracts for HotelOps AI.

This package defines the stable, versioned vocabulary that connects
every HotelOps AI module. All cross-module communication uses these
canonical types. Do NOT redefine them inside consuming modules.
"""

# Re-export common primitives for convenient access
# Re-export audit contracts
from contracts.audit import AuditActionCategory, AuditEvent
from contracts.common import (
    SCHEMA_VERSION,
    ActionCommandId,
    AlertId,
    AnalysisJobId,
    ApprovalRequestId,
    AuditEventId,
    CameraId,
    ConfigurationId,
    ConfigurationVersionId,
    DetectionId,
    EventId,
    EvidenceId,
    FindingId,
    FrameId,
    InboxMessageId,
    IntegrationId,
    MediaId,
    MembershipId,
    OpportunityId,
    OutboxMessageId,
    RecommendationId,
    RoleId,
    TenantId,
    TrackId,
    UserId,
    VenueId,
    VideoAssetId,
    VideoSessionId,
    new_uuid,
    parse_utc,
    serialize_utc,
    to_utc,
    utc_now,
    validate_schema_version,
    validate_utc,
)

# Re-export identity/tenancy contracts
from contracts.identity import (
    ActorContext,
    Membership,
    MembershipScope,
    MembershipStatus,
    Permission,
    Role,
    RoleName,
    Tenant,
    TenantStatus,
    User,
    UserStatus,
    Venue,
    VenueStatus,
    permissions_for_role,
)

# Re-export media contracts
from contracts.media import (
    MediaCategory,
    MediaLifecycleState,
    MediaProvenance,
    MediaUploadInitiateRequest,
    MediaUploadInitiateResponse,
)

# Re-export operational vertical-slice API contracts (Task 18.12/18.13)
from contracts.operational import (
    EvidenceAvailabilityResponse,
    OccupancyEventResponse,
    OccupancyFactResponse,
)

__all__ = [
    "SCHEMA_VERSION",
    "ActionCommandId",
    "ActorContext",
    "AlertId",
    "AnalysisJobId",
    "ApprovalRequestId",
    "AuditActionCategory",
    "AuditEvent",
    "AuditEventId",
    "CameraId",
    "ConfigurationId",
    "ConfigurationVersionId",
    "DetectionId",
    "EventId",
    "EvidenceAvailabilityResponse",
    "EvidenceId",
    "FindingId",
    "FrameId",
    "InboxMessageId",
    "IntegrationId",
    "MediaCategory",
    "MediaId",
    "MediaLifecycleState",
    "MediaProvenance",
    "MediaUploadInitiateRequest",
    "MediaUploadInitiateResponse",
    "Membership",
    "MembershipId",
    "MembershipScope",
    "MembershipStatus",
    "OccupancyEventResponse",
    "OccupancyFactResponse",
    "OpportunityId",
    "OutboxMessageId",
    "Permission",
    "RecommendationId",
    "Role",
    "RoleId",
    "RoleName",
    "Tenant",
    "TenantId",
    "TenantStatus",
    "TrackId",
    "User",
    "UserId",
    "UserStatus",
    "Venue",
    "VenueId",
    "VenueStatus",
    "VideoAssetId",
    "VideoSessionId",
    "new_uuid",
    "parse_utc",
    "permissions_for_role",
    "serialize_utc",
    "to_utc",
    "utc_now",
    "validate_schema_version",
    "validate_utc",
]
